
version: '3.6'
services:
  telegraf_assy:
    image: telegraf
    privileged: true
    container_name: telegraf_assy
    restart: always
    volumes:
    - ./telegraf_assy.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb_assy
    links:
      - influxdb_assy
    ports:
    - '8126:8125'

  influxdb_assy:
    image: influxdb:1.8-alpine
    container_name: influxdb_assy
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8087:8086'
    volumes:
      - influxdb_data_assy:/var/lib/influxdb

  telegraf_gd:
    image: telegraf
    privileged: true
    container_name: telegraf_gd
    restart: always
    volumes:
    - ./telegraf_gd.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb_gd
    links:
      - influxdb_gd
    ports:
    - '8127:8125'

  influxdb_gd:
    image: influxdb:1.8-alpine
    container_name: influxdb_gd
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8088:8086'
    volumes:
      - influxdb_data_gd:/var/lib/influxdb

  telegraf_sl:
    image: telegraf
    privileged: true
    container_name: telegraf_sl
    restart: always
    volumes:
    - ./telegraf_sl.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb_sl
    links:
      - influxdb_sl
    ports:
    - '8128:8125'

  influxdb_sl:
    image: influxdb:1.8-alpine
    container_name: influxdb_sl
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8089:8086'
    volumes:
      - influxdb_data_sl:/var/lib/influxdb

volumes:
  # grafana_data: {}
  influxdb_data_assy: {}
  # grafana_data2: {}
  influxdb_data_gd: {}
  # grafana_data3: {}
  influxdb_data_sl: {}